[package]
name = "aerendem/spittin-monsters"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
knit = "sleitnick/knit@1.4.7"
signal = "sleitnick/signal@2.0.1"
timer = "sleitnick/timer@1.1.2"